// #### Generated By: http://www.cufonfonts.com ####
/*!
 * The following copyright notice may not be removed under any circumstances.
 * 
 * Designer:
 * Radja Lomas
 */

        /* custom */
        function adaptStyle() {
                var $scrWidth = $(window).width();
                var $scrHeight = $(window).height();
                var $scrollTop = $(window).scrollTop();
                var $infoText = $scrWidth + 'px x ' + $scrHeight + 'px <br />Scroll : ' + $scrollTop + 'px <br> ' + navigator.userAgent ;
                if ( $scrWidth >= 960) {
                        $('.rd').addClass('desktop');
                } else if  ($scrWidth < 960) {		
                                $('.rd').removeClass('desktop');
                }
                //alert($infoTxt);
                return $infoText;
        }
        
        // Execute on load
        $(document).ready(adaptStyle());
        // Bind event listener
        $(window).resize(function() {
                try
                  {
                  adaptStyle();
                  }
                catch(err)
                  {
                  txt="There was an error on this page.\n\n";
                  txt+="Error description: " + err.message + "\n\n";
                  txt+="Click OK to continue.\n\n";
                  alert(txt);
                  }
                }
        );

        /*** sniff the UA of the client and show hidden div's for that device ***/
        var customizeForDevice = function(){
                var ua = navigator.userAgent;
                var checker = {
                  iphone: ua.match(/(iPhone|iPod|iPad)/),
                  blackberry: ua.match(/BlackBerry/),
                  android: ua.match(/Android/)
                };
                if (checker.android){
                        $('.android-only').show();
                }
                else if (checker.iphone){
                        $('.idevice-only').show();
                }
                else if (checker.blackberry){
                        $('.berry-only').show();
                }
                else {
                        $('.unknown-device').show();
                }
        }